### ISSUE TITLE
Divs are not properly centered

### ISSUE THREAD

**Issue by esstewart** [estewdotart/RGB-Guessing-Game#2]
The title bar and game board are appearing slightly further right from the center of the control bar.

**Comment by esstewart** [comment]
Looking at it, looks like it's just the message text that is _appearing_ to be askew from the rest of the control bar buttons--naturally the difficulty buttons are taking up more space than the NEW COLORS button, pushing the message text to the left so it doesn't appear to be centered with the squares. Making the message text width 15% from 20% and setting its padding-left to 85px improves this somewhat.

**Comment by samplek** [comment]
Hello! I've created a pull request with my suggestions for styling. I think that because the mode buttons are longer than the other 2 elements, it will be difficult to get it exactly centered.

Moving the text out of the control bar may help the layout look at little more centered. Let me know what you think!

**Comment by esstewart** [comment]
Message text looks better now, thanks! Looks like I'll need to set the height of mode-button-wrapper to 30px to have the buttons fill out that new div space, but easily done.
